# Generated by Django 5.2.17 on 2026-10-05 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('source_text', models.TextField()),
                ('ai_mode', models.CharField(default='mock', max_length=20)),
                ('ai_notice', models.CharField(blank=True, max_length=240)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('multiple_choice', 'multiple_choice'), ('short_answer', 'short_answer')], max_length=20)),
                ('text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('expected', models.TextField()),
                ('source_quote', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizapp.quiz')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_count', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('ai_mode', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quizapp.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField(blank=True)),
                ('expected', models.TextField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=20)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('verdict', models.CharField(max_length=12)),
                ('credit', models.FloatField()),
                ('justification', models.TextField()),
                ('ai_mode', models.CharField(max_length=20)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizapp.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizapp.question')),
            ],
            options={
                'ordering': ['question__position'],
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['owner', 'status'], name='quizapp_qui_owner_i_a376fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'position'), name='unique_question_position'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-created_at'], name='quizapp_qui_user_id_883c4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_user_submission'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='score_range'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_answer'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0), ('credit__lte', 1)), name='credit_range'),
        ),
    ]
