/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaterialRouteImport } from './routes/material'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as ReviewIdRouteImport } from './routes/review.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const MaterialRoute = MaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => rootRouteImport,
})
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
})
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
})
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
})
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
})
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
})
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MaterialRoute: MaterialRoute,
  ProfileRoute: ProfileRoute,
  QuizzesRoute: QuizzesRoute,
  RegisterRoute: RegisterRoute,
  QuizIdRoute: QuizIdRoute,
  ResultsIdRoute: ResultsIdRoute,
  ReviewIdRoute: ReviewIdRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
